Repository tari-project/universe, pull requests merged in 2024-09, with the labels that each got.

#394 feat(ui): settings tabs
  public/locales/en/settings.json
  src/components/MoneroAddressInput/MoneroAddressInput.styles.tsx
  src/components/elements/Tabs.styles.ts
  src/components/elements/Tabs.tsx
  src/containers/SideBar/components/Settings/DebugSettings.tsx
  src/containers/SideBar/components/Settings/HardwareStatus.tsx
  src/containers/SideBar/components/Settings/LogsSettings.tsx
  src/containers/SideBar/components/Settings/Settings.styles.tsx
  src/containers/SideBar/components/Settings/Settings.tsx
  src/theme/tokens.ts
Labels: p-controversial

#310 fix(config): remove app config versioning
  src-tauri/src/app_config.rs
  src-tauri/src/main.rs
  src-tauri/src/tests/app_config_tests.rs
  src-tauri/src/tests/mod.rs
Labels: p-controversial, p-high-risk

#371 chore(xmrig): use github releases for xmrig
  src-tauri/src/binary_resolver.rs
  src-tauri/src/github/mod.rs
  src-tauri/src/xmrig/latest_release.rs
  src-tauri/src/xmrig_adapter.rs
Labels: p-high-risk

#493 chore(stores): split get status command & refactor stores
  src-tauri/src/main.rs
  src-tauri/src/xmrig_adapter.rs
  src/App.tsx
  src/containers/Airdrop/AirdropPermission/AirdropPermission.tsx
  src/containers/Airdrop/AirdropPermissionSettings/AirdropPermissionSettings.tsx
  src/containers/Dashboard/MiningView/components/BlockHeightAccent.tsx
  src/containers/Dashboard/MiningView/components/BlockTime.tsx
  src/containers/Dashboard/MiningView/components/Earnings.tsx
  src/containers/Dashboard/MiningView/components/MiningButton.tsx
  src/containers/Dashboard/MiningView/components/Ruler.tsx
  src/containers/Dashboard/SetupView/SetupViewContainer.tsx
  src/containers/Error/ErrorSnackbar.tsx
  src/containers/SideBar/Miner/Miner.tsx
  src/containers/SideBar/Miner/components/ModeSelect.tsx
  src/containers/SideBar/components/Heading.tsx
  src/containers/SideBar/components/Settings/AppVersions.tsx
  src/containers/SideBar/components/Settings/DebugSettings.tsx
  src/containers/SideBar/components/Settings/HardwareStatus.tsx
  src/containers/SideBar/components/Settings/Markups/CpuMiningMarkup.tsx
  src/containers/SideBar/components/Settings/Markups/GpuMiningMarkup.tsx
  src/containers/SideBar/components/Settings/Markups/MoneroAddressMarkup/MoneroAddressMarkup.tsx
  src/containers/SideBar/components/Settings/Markups/P2pMarkup.tsx
  src/containers/SideBar/components/Settings/Markups/P2poolStatsMarkup.tsx
  src/containers/SideBar/components/Settings/Markups/WalletAddressMarkup.tsx
  src/containers/SideBar/components/Settings/SettingsButton.tsx
  src/containers/SideBar/components/Settings/SettingsDialog.tsx
  src/containers/SideBar/components/Wallet.tsx
  src/hooks/mining/useBalanceChanges.ts
  src/hooks/mining/useBlockInfo.ts
  src/hooks/mining/useMiningControls.ts
  src/hooks/mining/useMiningUiStateMachine.ts
  src/hooks/mining/useVisualisation.ts
  src/hooks/useEnvironment.ts
  src/hooks/useGetStatus.ts
  src/hooks/useHardwareStats.ts
  src/hooks/useHardwareStatus.ts
  src/hooks/useMiningMetricsUpdater.ts
  src/hooks/useSetUp.ts
  src/hooks/useVersions.ts
  src/hooks/useWalletUpdater.ts
  src/store/appStateStore.ts
  src/store/useAppConfigStore.ts
  src/store/useAppStatusStore.ts
  src/store/useBaseNodeStatusStore.ts
  src/store/useCPUStatusStore.ts
  src/store/useGPUStatusStore.ts
  src/store/useMiningStore.ts
  src/store/useP2poolStatsStore.ts
  src/store/useWalletStore.ts
  src/store/walletStore.ts
  src/types/app-status.ts
  src/types/invoke.ts
  src/utils/calculateTimeSince.ts
Labels: p-controversial, p-high-risk

#443 fix(setup): critical errors when setup application
  public/locales/af/common.json
  public/locales/cn/common.json
  public/locales/en/common.json
  public/locales/pl/common.json
  public/locales/tr/common.json
  src-tauri/src/binary_resolver.rs
  src-tauri/src/main.rs
  src-tauri/src/node_manager.rs
  src-tauri/src/p2pool_manager.rs
  src-tauri/src/xmrig_adapter.rs
  src/App.tsx
  src/containers/CriticalErrorDialog/CriticalErrorDialog.tsx
  src/hooks/useSetUp.ts
  src/store/appStateStore.ts
  src/types/invoke.ts
Labels: p-controversial

#500 refactor: store the passphrase without keyring
  src-tauri/src/internal_wallet.rs
Labels: p-controversial, p-high-risk

#259 chore: unify-binaries-reading-and-download
  src-tauri/binaries_versions.json
  src-tauri/src/binaries/adapter_github.rs
  src-tauri/src/binaries/adapter_xmrig.rs
  src-tauri/src/binaries/binaries_list.rs
  src-tauri/src/binaries/binaries_manager.rs
  src-tauri/src/binaries/binaries_resolver.rs
  src-tauri/src/binaries/mod.rs
  src-tauri/src/binary_resolver.rs
  src-tauri/src/cpu_miner.rs
  src-tauri/src/download_utils.rs
  src-tauri/src/github/mod.rs
  src-tauri/src/gpu_miner.rs
  src-tauri/src/gpu_miner_adapter.rs
  src-tauri/src/main.rs
  src-tauri/src/mm_proxy_adapter.rs
  src-tauri/src/node_adapter.rs
  src-tauri/src/p2pool_adapter.rs
  src-tauri/src/wallet_adapter.rs
  src-tauri/src/xmrig/latest_release.rs
  src-tauri/src/xmrig/mod.rs
  src-tauri/src/xmrig_adapter.rs
  src/hooks/useSetUp.ts
  src/store/appStateStore.ts
Labels: p-high-risk

#590 refactor(animations): blockchain animations
  src-tauri/src/node_manager.rs
  src/App.tsx
  src/containers/Dashboard/MiningView/components/BlockHeightAccent.tsx
  src/containers/Dashboard/MiningView/components/BlockTime.tsx
  src/containers/Dashboard/MiningView/components/Earnings.tsx
  src/containers/Dashboard/MiningView/components/Ruler.tsx
  src/containers/Dashboard/SetupView/SetupViewContainer.tsx
  src/containers/Settings/sections/experimental/DebugSettings.tsx
  src/containers/SideBar/components/Wallet.tsx
  src/hooks/mining/useBalanceChanges.ts
  src/hooks/mining/useBlockInfo.ts
  src/hooks/mining/useMining.ts
  src/hooks/mining/useMiningUiStateMachine.ts
  src/hooks/mining/useVisualisation.ts
  src/hooks/useSetUp.ts
  src/store/appStateStore.ts
  src/store/useBlockchainVisualisationStore.ts
  src/store/useMiningStore.ts
  src/utils/calculateTimeSince.ts
Labels: p-controversial
