Repository tari-project/universe, pull requests merged in 2025-03, with the labels that each got.

#1564 feat(ui): update reset modal UX x wording
  public/locales/af/settings.json
  public/locales/cn/settings.json
  public/locales/de/settings.json
  public/locales/en/settings.json
  public/locales/fr/settings.json
  public/locales/hi/settings.json
  public/locales/id/settings.json
  public/locales/ja/settings.json
  public/locales/ko/settings.json
  public/locales/pl/settings.json
  public/locales/ru/settings.json
  public/locales/tr/settings.json
  src/components/elements/buttons/BaseButton.styles.ts
  src/components/elements/inputs/RadioButton.styles.ts
  src/components/elements/inputs/RadioButton.tsx
  src/containers/floating/Settings/sections/general/ResetSettingsButton.tsx
  src/containers/floating/Settings/sections/general/ResetSettingsDialog.tsx
Labels: enhancement, a-ui

#1237 fix: app restarts after sleepmode
  public/locales/af/common.json
  public/locales/af/components.json
  public/locales/af/setup-view.json
  public/locales/cn/common.json
  public/locales/cn/components.json
  public/locales/cn/setup-view.json
  public/locales/de/common.json
  public/locales/de/components.json
  public/locales/de/setup-view.json
  public/locales/en/common.json
  public/locales/en/components.json
  public/locales/en/setup-view.json
  public/locales/fr/common.json
  public/locales/fr/components.json
  public/locales/fr/setup-view.json
  public/locales/hi/common.json
  public/locales/hi/components.json
  public/locales/hi/setup-view.json
  public/locales/id/common.json
  public/locales/id/components.json
  public/locales/id/setup-view.json
  public/locales/ja/common.json
  public/locales/ja/components.json
  public/locales/ja/setup-view.json
  public/locales/ko/common.json
  public/locales/ko/components.json
  public/locales/ko/setup-view.json
  public/locales/pl/common.json
  public/locales/pl/components.json
  public/locales/pl/setup-view.json
  public/locales/ru/common.json
  public/locales/ru/components.json
  public/locales/ru/setup-view.json
  public/locales/tr/common.json
  public/locales/tr/components.json
  public/locales/tr/setup-view.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/commands.rs
  src-tauri/src/events.rs
  src-tauri/src/main.rs
  src-tauri/src/updates_manager.rs
  src-tauri/src/utils/mod.rs
  src-tauri/src/utils/shutdown_utils.rs
  src-tauri/src/utils/system_status.rs
  src/App/AppEffects.tsx
  src/containers/floating/AutoUpdateDialog/AutoUpdateDialog.tsx
  src/containers/floating/FloatingElements.tsx
  src/containers/floating/ResumeApplicationModal/ResumeApplicationModal.tsx
  src/containers/floating/ResumeApplicationModal/styles.ts
  src/hooks/app/useListenForAppResuming.ts
  src/hooks/mining/useMiningUiStateMachine.ts
  src/store/appStateStore.ts
Labels: p-controversial

#897 feat: include vc in installer
  .github/workflows/release.yml
  .gitignore
  .license.ignore
  tari-win-bundler/Bundle.wxs
  tari-win-bundler/Tari Universe.wixproj
  tari-win-bundler/Tari Universe.wixproj.user
  tari-win-bundler/Theme.wxl
  tari-win-bundler/Theme.xml
  tari-win-bundler/resources/71x71.png
  tari-win-bundler/resources/clouds.bmp
  tari-win-bundler/resources/icon.ico
Labels: p-controversial

#1642 refactor: airdrop auth and WS
  eslint.config.js
  src/App/AppEffects.tsx
  src/containers/floating/ShareRewardModal/ShareRewardModal.tsx
  src/containers/main/Airdrop/AirdropGiftTracker/AirdropGiftTracker.tsx
  src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/LoggedIn.tsx
  src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Invite/Invite.tsx
  src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedOut/LoggedOut.tsx
  src/containers/main/SideBar/components/Wallet/HistoryItem.tsx
  src/containers/phase/Setup/Setup.tsx
  src/hooks/airdrop/stateHelpers/useAirdropTokensRefresh.ts
  src/hooks/airdrop/stateHelpers/useAirdropUserPointsListener.ts
  src/hooks/airdrop/stateHelpers/useFetchAirdropToken.ts
  src/hooks/airdrop/stateHelpers/useGetReferralQuestPoints.ts
  src/hooks/airdrop/stateHelpers/useGetSosReferrals.ts
  src/hooks/airdrop/useAirdropSyncState.ts
  src/hooks/airdrop/useWebsocket.ts
  src/hooks/airdrop/utils/useHandleRequest.ts
  src/hooks/airdrop/ws/useAirdropWebsocket.ts
  src/hooks/airdrop/ws/useHandleEmitMiningStatus.ts
  src/hooks/airdrop/ws/useHandleWsUserIdEvent.ts
  src/hooks/airdrop/ws/useSocket.ts
  src/hooks/app/useSetUp.ts
  src/store/actions/airdropStoreActions.ts
  src/store/actions/appStateStoreActions.ts
  src/store/actions/index.ts
  src/store/useAirdropStore.ts
  src/store/useShellOfSecretsStore.ts
  src/types/invoke.d.ts
  src/types/ws.ts
  src/utils/socket.ts
Labels: a-ui, javascript, stability

#1695 fix(ui): tower stop delay
  package-lock.json
  package.json
  src/App/App.tsx
  src/hooks/app/useSetUp.ts
  src/hooks/mining/useMiningUiStateMachine.ts
Labels: bug, a-ui, a-blocktower-animations, dependencies

#1712 chore: bump outdated dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript, stability

#1629 feat: add remote node proof of concept
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/log4rs/base_node_sample.yml
  src-tauri/src/app_config.rs
  src-tauri/src/commands.rs
  src-tauri/src/events_service.rs
  src-tauri/src/gpu_miner.rs
  src-tauri/src/gpu_miner_adapter.rs
  src-tauri/src/gpu_status_file.rs
  src-tauri/src/main.rs
  src-tauri/src/mm_proxy_adapter.rs
  src-tauri/src/mm_proxy_manager.rs
  src-tauri/src/node_adapter.rs
  src-tauri/src/node_manager.rs
  src-tauri/src/p2pool_adapter.rs
  src-tauri/src/p2pool_manager.rs
  src-tauri/src/process_adapter.rs
  src-tauri/src/process_watcher.rs
  src-tauri/src/remote_node_adapter.rs
  src-tauri/src/remote_until_synced_node_adapter.rs
  src-tauri/src/spend_wallet_adapter.rs
  src-tauri/src/spend_wallet_manager.rs
  src-tauri/src/telemetry_manager.rs
  src-tauri/src/tor_adapter.rs
  src-tauri/src/utils/shutdown_utils.rs
  src-tauri/src/wallet_adapter.rs
  src-tauri/src/wallet_manager.rs
  src-tauri/src/xmrig_adapter.rs
Labels: enhancement
