Repository tari-project/universe, pull requests merged in 2025-06, with the labels that each got.

#2262 fix: stringhandler todos (first batch)
  src-tauri/src/main.rs
  src-tauri/src/process_adapter_utils.rs
  src-tauri/src/process_watcher.rs
  src-tauri/src/setup/phase_wallet.rs
  src-tauri/src/telemetry_manager.rs
  src-tauri/src/wallet_adapter.rs
  src-tauri/src/wallet_manager.rs
Labels: TD-todos

#2325 feat: timeout improvements for binaries
  public/locales/af/setup-progresses.json
  public/locales/cn/setup-progresses.json
  public/locales/de/setup-progresses.json
  public/locales/en/setup-progresses.json
  public/locales/fr/setup-progresses.json
  public/locales/hi/setup-progresses.json
  public/locales/id/setup-progresses.json
  public/locales/ja/setup-progresses.json
  public/locales/ko/setup-progresses.json
  public/locales/pl/setup-progresses.json
  public/locales/ru/setup-progresses.json
  public/locales/tr/setup-progresses.json
  src-tauri/binaries-versions/binaries_versions_mainnet.json
  src-tauri/binaries-versions/binaries_versions_nextnet.json
  src-tauri/binaries-versions/binaries_versions_testnets.json
  src-tauri/src/binaries/adapter_bridge.rs
  src-tauri/src/binaries/adapter_github.rs
  src-tauri/src/binaries/adapter_tor.rs
  src-tauri/src/binaries/adapter_xmrig.rs
  src-tauri/src/binaries/binaries_list.rs
  src-tauri/src/binaries/binaries_manager.rs
  src-tauri/src/binaries/binaries_resolver.rs
  src-tauri/src/binaries/mod.rs
  src-tauri/src/commands.rs
  src-tauri/src/github/request_client.rs
  src-tauri/src/main.rs
  src-tauri/src/progress_tracker_old.rs
  src-tauri/src/setup/phase_hardware.rs
  src-tauri/src/setup/phase_mining.rs
  src-tauri/src/setup/phase_node.rs
  src-tauri/src/setup/phase_wallet.rs
  src-tauri/src/tapplets/mod.rs
  src-tauri/src/tapplets/tapplets_list.rs
  src-tauri/src/tapplets/tapplets_manager.rs
  src-tauri/src/tapplets/tapplets_resolver.rs
  src/containers/floating/ResumeApplicationModal/ResumeApplicationModal.tsx
  src/containers/floating/Settings/sections/experimental/AppVersions.tsx
  src/containers/main/Sync/components/Progress.tsx
  src/store/actions/appStateStoreActions.ts
  src/store/actions/index.ts
  src/types/invoke.d.ts
Labels: enhancement

#2350 feat: redesign exchange address modal
  index.html
  public/assets/fonts/FugazOne/FugazOne-Regular.ttf
  public/assets/img/TU-logo.svg
  public/assets/img/copy-clipboard.svg
  public/assets/img/exchange_miner_header.png
  public/assets/img/wrapped_gift.svg
  public/locales/af/exchange.json
  public/locales/cn/exchange.json
  public/locales/de/exchange.json
  public/locales/en/exchange.json
  public/locales/fr/exchange.json
  public/locales/hi/exchange.json
  public/locales/id/exchange.json
  public/locales/ja/exchange.json
  public/locales/ko/exchange.json
  public/locales/pl/exchange.json
  public/locales/ru/exchange.json
  public/locales/tr/exchange.json
  src-tauri/capabilities/default.json
  src-tauri/src/commands.rs
  src-tauri/src/events_emitter.rs
  src-tauri/src/setup/setup_manager.rs
  src-tauri/tauri.conf.json
  src/assets/icons/chevron.tsx
  src/components/exchanges/commonStyles.ts
  src/components/exchanges/universal/clipboardViewer/ClipboardViewer.tsx
  src/components/exchanges/universal/clipboardViewer/styles.ts
  src/components/exchanges/universal/exchangeAddress/ExchangeAddress.tsx
  src/components/exchanges/universal/exchangeAddress/styles.ts
  src/components/exchanges/universal/option/XCOption.tsx
  src/components/exchanges/universal/option/styles.ts
  src/components/exchanges/universal/options/Options.tsx
  src/components/exchanges/universal/options/styles.ts
  src/containers/floating/EXModal/components/Content.tsx
  src/containers/floating/EXModal/components/Hero.tsx
  src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/WalletAddressMarkup.tsx
  src/containers/floating/UniversalEXSelectorModal/UniversalEXSelectorModal.tsx
  src/containers/floating/UniversalEXSelectorModal/styles.ts
  src/containers/floating/XSpaceBanner/XSpaceBanner.style.ts
  src/containers/navigation/Sidebars/SidebarMini.tsx
  src/store/actions/appConfigStoreActions.ts
  src/store/actions/setupStoreActions.ts
  src/store/useExchangeStore.ts
  src/types/exchange.ts
  src/types/invoke.d.ts
  src/utils/formatters.ts
Labels: enhancement

#2450 fix(ui): debug block time display
  public/locales/af/settings.json
  public/locales/cn/settings.json
  public/locales/de/settings.json
  public/locales/en/settings.json
  public/locales/fr/settings.json
  public/locales/hi/settings.json
  public/locales/id/settings.json
  public/locales/ja/settings.json
  public/locales/ko/settings.json
  public/locales/pl/settings.json
  public/locales/ru/settings.json
  public/locales/tr/settings.json
  src/containers/floating/Settings/sections/experimental/DebugSettings.tsx
  src/hooks/mining/useBlockInfo.ts
Labels: bug, a-ui, javascript

#2440 chore(ui): implement react updates - `useTransition` [FE Tech Debt]
  src/components/dialogs/RestartDialog.tsx
  src/components/dialogs/SendLogsDialog.tsx
  src/components/wallet/seedwords/SeedWords.tsx
  src/containers/floating/PaperWalletModal/sections/ConnectSection/ConnectSection.tsx
  src/containers/floating/Settings/sections/airdrop/ApplyInviteCode.tsx
  src/containers/floating/Settings/sections/general/AppDataSettings.tsx
  src/containers/floating/Settings/sections/general/LogsSettings.tsx
  src/containers/floating/Settings/sections/general/ResetSettingsDialog.tsx
  src/containers/main/Airdrop/Settings/Logout.tsx
  src/containers/main/Airdrop/Settings/styles.ts
Labels: a-ui, javascript, stability, TD-todos

#2441 chore(ui): implement react updates - error boundary | preload [FE TD]
  index.html
  src/App/App.tsx
  src/App/AppWrapper.tsx
  src/containers/main/Dashboard/components/BlockExplorerMini/BlockEntry/BlockSolving/BlockVideo/BlockVideo.tsx
  src/containers/main/Sync/Sync.tsx
  src/main.tsx
  src/theme/GlobalStyle.ts
Labels: a-ui, javascript, stability, TD-todos

#2451 chore(ui): [FE TD] Tari address validation
  src/components/exchanges/connect/Connect.tsx
  src/components/exchanges/universal/clipboardViewer/ClipboardViewer.tsx
  src/components/exchanges/universal/exchangeAddress/ExchangeAddress.tsx
  src/components/transactions/send/SendForm.tsx
  src/components/wallet/components/balance/WalletBalance.tsx
  src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/WalletAddressMarkup.tsx
  src/hooks/wallet/useTariBalance.ts
  src/hooks/wallet/useValidate.ts
Labels: a-ui, javascript, TD-todos

#2298 feat: tx history tabs
  public/locales/af/wallet.json
  public/locales/cn/wallet.json
  public/locales/de/wallet.json
  public/locales/en/wallet.json
  public/locales/fr/wallet.json
  public/locales/hi/wallet.json
  public/locales/id/wallet.json
  public/locales/ja/wallet.json
  public/locales/ko/wallet.json
  public/locales/pl/wallet.json
  public/locales/ru/wallet.json
  public/locales/tr/wallet.json
  src-tauri/src/commands.rs
  src-tauri/src/main.rs
  src-tauri/src/wallet_adapter.rs
  src-tauri/src/wallet_manager.rs
  src/components/elements/buttons/TextButton.tsx
  src/components/elements/inputs/Select.tsx
  src/components/transactions/history/FilterSelect.tsx
  src/components/transactions/history/List.styles.ts
  src/components/wallet/sidebarWallet/SidebarWallet.tsx
  src/components/wallet/sidebarWallet/styles.ts
  src/hooks/wallet/useFetchTxHistory.ts
  src/store/actions/index.ts
  src/store/actions/setupStoreActions.ts
  src/store/actions/walletStoreActions.ts
  src/store/useWalletStore.ts
  src/types/invoke.d.ts
Labels: enhancement
